stages:
    - build
    - develop
stage_dev:
    stage: develop
    tags:
        - django-dev-shell
    script:
        - cd /
        - cd /home/itsuppus/svetorezerv/buyerdev/
        #удаляем изменения
        #- git stash
        #- git stash drop
        #получаем из git новую версию
        - git pull
        #Удалить лишние миграции
        - rm -f /home/itsuppus/svetorezerv/buyerdev/app/migrations/0001_initial.py
        #создаём базу
        - sudo -u postgres psql -f init.sql
        #обновить миграции
        - /home/itsuppus/svetorezerv/buyerdev/venv/bin/python /home/itsuppus/svetorezerv/buyerdev/venv/bin/pip install -r ./requirements.txt
        - /home/itsuppus/svetorezerv/buyerdev/venv/bin/python manage.py migrate
        #собрать статику
        - /home/itsuppus/svetorezerv/buyerdev/venv/bin/python manage.py collectstatic --no-input
        - cd /home/itsuppus/svetorezerv/buyerdev/textBlockClassifier/
        - docker rm -f /textBlockClassifier
        - docker build -t textblockclassifier .
        - docker run --restart=always -d -it -p 127.0.0.1:8000:8000 --name textBlockClassifier textblockclassifier
    when: manual
