version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn Buyer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - . :/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data.prod/
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - app
  rabbit:
    restart: always
    image: "rabbitmq:3-management"
    env_file:
      - ./.env
#Web Interface Rabbitmq
#    ports:
#      - "15672:15672"
volumes:
  postgres_data:
  static_volume:
  media_volume: